name: My First Records
author: ice1039
baseurl: /herring-cove
description: My techblog
github: github.com/ice1039
email: icyforest0919@gmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
